[package]
name = "lilia-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
lilia-core = { path = "../../crates/lilia-core" }
lilia-storage-sqlite = { path = "../../crates/lilia-storage-sqlite" }
lilia-plugin-api = { path = "../../crates/lilia-plugin-api" }
lilia-protocol = { path = "../../crates/lilia-protocol" }
rand.workspace = true
serde_json.workspace = true
subtle = "2.6.1"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
